"""City-to-IANA timezone mapping for Eddie's clock tool.

Ported from the original ActionLayer/timezones.py.
"""

TIMEZONES: dict[str, str] = {
    "abidjan": "Africa/Abidjan",
    "accra": "Africa/Accra",
    "addis ababa": "Africa/Addis_Ababa",
    "adelaide": "Australia/Adelaide",
    "algiers": "Africa/Algiers",
    "almaty": "Asia/Almaty",
    "amman": "Asia/Amman",
    "amsterdam": "Europe/Amsterdam",
    "anchorage": "America/Anchorage",
    "ankara": "Europe/Istanbul",
    "antananarivo": "Indian/Antananarivo",
    "auckland": "Pacific/Auckland",
    "baghdad": "Asia/Baghdad",
    "bahrain": "Asia/Bahrain",
    "baku": "Asia/Baku",
    "bangkok": "Asia/Bangkok",
    "barcelona": "Europe/Madrid",
    "beijing": "Asia/Shanghai",
    "beirut": "Asia/Beirut",
    "belgrade": "Europe/Belgrade",
    "berlin": "Europe/Berlin",
    "bogota": "America/Bogota",
    "bratislava": "Europe/Bratislava",
    "brisbane": "Australia/Brisbane",
    "brussels": "Europe/Brussels",
    "bucharest": "Europe/Bucharest",
    "budapest": "Europe/Budapest",
    "buenos aires": "America/Argentina/Buenos_Aires",
    "cairo": "Africa/Cairo",
    "canberra": "Australia/Canberra",
    "cape town": "Africa/Johannesburg",
    "caracas": "America/Caracas",
    "casablanca": "Africa/Casablanca",
    "cheltenham": "Europe/London",
    "chicago": "America/Chicago",
    "colombo": "Asia/Colombo",
    "copenhagen": "Europe/Copenhagen",
    "dakar": "Africa/Dakar",
    "damascus": "Asia/Damascus",
    "dar es salaam": "Africa/Dar_es_Salaam",
    "darwin": "Australia/Darwin",
    "delhi": "Asia/Kolkata",
    "denver": "America/Denver",
    "detroit": "America/Detroit",
    "dhaka": "Asia/Dhaka",
    "doha": "Asia/Qatar",
    "dubai": "Asia/Dubai",
    "dublin": "Europe/Dublin",
    "edinburgh": "Europe/London",
    "frankfurt": "Europe/Berlin",
    "geneva": "Europe/Zurich",
    "hanoi": "Asia/Ho_Chi_Minh",
    "havana": "America/Havana",
    "helsinki": "Europe/Helsinki",
    "ho chi minh": "Asia/Ho_Chi_Minh",
    "hobart": "Australia/Hobart",
    "hong kong": "Asia/Hong_Kong",
    "honolulu": "Pacific/Honolulu",
    "houston": "America/Chicago",
    "istanbul": "Europe/Istanbul",
    "jakarta": "Asia/Jakarta",
    "jerusalem": "Asia/Jerusalem",
    "johannesburg": "Africa/Johannesburg",
    "kabul": "Asia/Kabul",
    "karachi": "Asia/Karachi",
    "kathmandu": "Asia/Kathmandu",
    "kiev": "Europe/Kyiv",
    "kolkata": "Asia/Kolkata",
    "kuala lumpur": "Asia/Kuala_Lumpur",
    "kuwait": "Asia/Kuwait",
    "kyiv": "Europe/Kyiv",
    "lagos": "Africa/Lagos",
    "lahore": "Asia/Karachi",
    "lima": "America/Lima",
    "lisbon": "Europe/Lisbon",
    "london": "Europe/London",
    "los angeles": "America/Los_Angeles",
    "madrid": "Europe/Madrid",
    "manila": "Asia/Manila",
    "melbourne": "Australia/Melbourne",
    "mexico city": "America/Mexico_City",
    "miami": "America/New_York",
    "milan": "Europe/Rome",
    "minsk": "Europe/Minsk",
    "mojacar": "Europe/Madrid",
    "montreal": "America/Montreal",
    "moscow": "Europe/Moscow",
    "mumbai": "Asia/Kolkata",
    "munich": "Europe/Berlin",
    "muscat": "Asia/Muscat",
    "nairobi": "Africa/Nairobi",
    "new york": "America/New_York",
    "osaka": "Asia/Tokyo",
    "oslo": "Europe/Oslo",
    "ottawa": "America/Toronto",
    "paris": "Europe/Paris",
    "perth": "Australia/Perth",
    "phoenix": "America/Phoenix",
    "port talbot": "Europe/London",
    "prague": "Europe/Prague",
    "reykjavik": "Atlantic/Reykjavik",
    "riga": "Europe/Riga",
    "rio de janeiro": "America/Sao_Paulo",
    "riyadh": "Asia/Riyadh",
    "rome": "Europe/Rome",
    "san francisco": "America/Los_Angeles",
    "santiago": "America/Santiago",
    "sao paulo": "America/Sao_Paulo",
    "seattle": "America/Los_Angeles",
    "seoul": "Asia/Seoul",
    "shanghai": "Asia/Shanghai",
    "sheffield": "Europe/London",
    "singapore": "Asia/Singapore",
    "sofia": "Europe/Sofia",
    "stockholm": "Europe/Stockholm",
    "sydney": "Australia/Sydney",
    "taipei": "Asia/Taipei",
    "tallinn": "Europe/Tallinn",
    "tashkent": "Asia/Tashkent",
    "tehran": "Asia/Tehran",
    "tel aviv": "Asia/Tel_Aviv",
    "tokyo": "Asia/Tokyo",
    "toronto": "America/Toronto",
    "vancouver": "America/Vancouver",
    "vienna": "Europe/Vienna",
    "vilnius": "Europe/Vilnius",
    "warsaw": "Europe/Warsaw",
    "washington": "America/New_York",
    "wellington": "Pacific/Auckland",
    "winnipeg": "America/Winnipeg",
    "york": "Europe/London",
    "zagreb": "Europe/Zagreb",
    "zurich": "Europe/Zurich",
}
