timezones = {"abidjan":"Africa/Abidjan",
"accra":"Africa/Accra",
"acre":"Brazil/Acre",
"act":"Australia/ACT",
"adak":"America/Adak",
"addis ababa":"Africa/Addis_Ababa",
"adelaide":"Australia/Adelaide",
"aden":"Asia/Aden",
"alaska":"US/Alaska",
"aleutian":"US/Aleutian",
"algiers":"Africa/Algiers",
"almaty":"Asia/Almaty",
"amman":"Asia/Amman",
"amsterdam":"Europe/Amsterdam",
"anadyr":"Asia/Anadyr",
"anchorage":"America/Anchorage",
"andorra":"Europe/Andorra",
"anguilla":"America/Anguilla",
"antananarivo":"Indian/Antananarivo",
"antigua":"America/Antigua",
"apia":"Pacific/Apia",
"aqtau":"Asia/Aqtau",
"aqtobe":"Asia/Aqtobe",
"araguaina":"America/Araguaina",
"arizona":"US/Arizona",
"aruba":"America/Aruba",
"ashgabat":"Asia/Ashgabat",
"ashkhabad":"Asia/Ashkhabad",
"asmara":"Africa/Asmara",
"asmera":"Africa/Asmera",
"astrakhan":"Europe/Astrakhan",
"asuncion":"America/Asuncion",
"athens":"Europe/Athens",
"atikokan":"America/Atikokan",
"atka":"America/Atka",
"atlantic":"Canada/Atlantic",
"atyrau":"Asia/Atyrau",
"auckland":"Pacific/Auckland",
"azores":"Atlantic/Azores",
"baghdad":"Asia/Baghdad",
"bahia":"America/Bahia",
"bahia banderas":"America/Bahia_Banderas",
"bahrain":"Asia/Bahrain",
"bajanorte":"Mexico/BajaNorte",
"bajasur":"Mexico/BajaSur",
"baku":"Asia/Baku",
"bamako":"Africa/Bamako",
"bangkok":"Asia/Bangkok",
"bangui":"Africa/Bangui",
"banjul":"Africa/Banjul",
"barbados":"America/Barbados",
"barnaul":"Asia/Barnaul",
"beirut":"Asia/Beirut",
"belem":"America/Belem",
"belfast":"Europe/Belfast",
"belgrade":"Europe/Belgrade",
"belize":"America/Belize",
"berlin":"Europe/Berlin",
"bermuda":"Atlantic/Bermuda",
"beulah":"America/North_Dakota/Beulah",
"bishkek":"Asia/Bishkek",
"bissau":"Africa/Bissau",
"blanc-sablon":"America/Blanc-Sablon",
"blantyre":"Africa/Blantyre",
"boa vista":"America/Boa_Vista",
"bogota":"America/Bogota",
"boise":"America/Boise",
"bougainville":"Pacific/Bougainville",
"bratislava":"Europe/Bratislava",
"brazzaville":"Africa/Brazzaville",
"brisbane":"Australia/Brisbane",
"broken hill":"Australia/Broken_Hill",
"brunei":"Asia/Brunei",
"brussels":"Europe/Brussels",
"bucharest":"Europe/Bucharest",
"budapest":"Europe/Budapest",
"buenos aires":"America/Argentina/Buenos_Aires",
"buenos aires":"America/Buenos_Aires",
"bujumbura":"Africa/Bujumbura",
"busingen":"Europe/Busingen",
"cairo":"Africa/Cairo",
"calcutta":"Asia/Calcutta",
"cambridge bay":"America/Cambridge_Bay",
"campo grande":"America/Campo_Grande",
"canary":"Atlantic/Canary",
"canberra":"Australia/Canberra",
"cancun":"America/Cancun",
"cape verde":"Atlantic/Cape_Verde",
"caracas":"America/Caracas",
"casablanca":"Africa/Casablanca",
"casey":"Antarctica/Casey",
"catamarca":"America/Argentina/Catamarca",
"catamarca":"America/Catamarca",
"cayenne":"America/Cayenne",
"cayman":"America/Cayman",
"center":"America/North_Dakota/Center",
"central":"Canada/Central",
"central":"US/Central",
"ceuta":"Africa/Ceuta",
"chagos":"Indian/Chagos",
"chatham":"Pacific/Chatham",
"chicago":"America/Chicago",
"chihuahua":"America/Chihuahua",
"chisinau":"Europe/Chisinau",
"chita":"Asia/Chita",
"choibalsan":"Asia/Choibalsan",
"chongqing":"Asia/Chongqing",
"christmas":"Indian/Christmas",
"chungking":"Asia/Chungking",
"chuuk":"Pacific/Chuuk",
"ciudad juarez":"America/Ciudad_Juarez",
"cocos":"Indian/Cocos",
"colombo":"Asia/Colombo",
"comodrivadavia":"America/Argentina/ComodRivadavia",
"comoro":"Indian/Comoro",
"conakry":"Africa/Conakry",
"continental":"Chile/Continental",
"copenhagen":"Europe/Copenhagen",
"coral harbour":"America/Coral_Harbour",
"cordoba":"America/Argentina/Cordoba",
"cordoba":"America/Cordoba",
"costa rica":"America/Costa_Rica",
"creston":"America/Creston",
"cuiaba":"America/Cuiaba",
"curacao":"America/Curacao",
"currie":"Australia/Currie",
"dacca":"Asia/Dacca",
"dakar":"Africa/Dakar",
"damascus":"Asia/Damascus",
"danmarkshavn":"America/Danmarkshavn",
"dar es salaam":"Africa/Dar_es_Salaam",
"darwin":"Australia/Darwin",
"davis":"Antarctica/Davis",
"dawson":"America/Dawson",
"dawson creek":"America/Dawson_Creek",
"denoronha":"Brazil/DeNoronha",
"denver":"America/Denver",
"detroit":"America/Detroit",
"dhaka":"Asia/Dhaka",
"dili":"Asia/Dili",
"djibouti":"Africa/Djibouti",
"dominica":"America/Dominica",
"douala":"Africa/Douala",
"dubai":"Asia/Dubai",
"dublin":"Europe/Dublin",
"dumontdurville":"Antarctica/DumontDUrville",
"dushanbe":"Asia/Dushanbe",
"east":"Brazil/East",
"east-indiana":"US/East-Indiana",
"easter":"Pacific/Easter",
"easterisland":"Chile/EasterIsland",
"eastern":"Canada/Eastern",
"eastern":"US/Eastern",
"edmonton":"America/Edmonton",
"efate":"Pacific/Efate",
"eirunepe":"America/Eirunepe",
"el aaiun":"Africa/El_Aaiun",
"el salvador":"America/El_Salvador",
"enderbury":"Pacific/Enderbury",
"ensenada":"America/Ensenada",
"eucla":"Australia/Eucla",
"faeroe":"Atlantic/Faeroe",
"fakaofo":"Pacific/Fakaofo",
"famagusta":"Asia/Famagusta",
"faroe":"Atlantic/Faroe",
"fiji":"Pacific/Fiji",
"fort nelson":"America/Fort_Nelson",
"fort wayne":"America/Fort_Wayne",
"fortaleza":"America/Fortaleza",
"freetown":"Africa/Freetown",
"funafuti":"Pacific/Funafuti",
"gaborone":"Africa/Gaborone",
"galapagos":"Pacific/Galapagos",
"gambier":"Pacific/Gambier",
"gaza":"Asia/Gaza",
"general":"Mexico/General",
"gibraltar":"Europe/Gibraltar",
"glace bay":"America/Glace_Bay",
"godthab":"America/Godthab",
"goose bay":"America/Goose_Bay",
"grand turk":"America/Grand_Turk",
"grenada":"America/Grenada",
"guadalcanal":"Pacific/Guadalcanal",
"guadeloupe":"America/Guadeloupe",
"guam":"Pacific/Guam",
"guatemala":"America/Guatemala",
"guayaquil":"America/Guayaquil",
"guernsey":"Europe/Guernsey",
"guyana":"America/Guyana",
"halifax":"America/Halifax",
"harare":"Africa/Harare",
"harbin":"Asia/Harbin",
"havana":"America/Havana",
"hawaii":"US/Hawaii",
"hebron":"Asia/Hebron",
"helsinki":"Europe/Helsinki",
"hermosillo":"America/Hermosillo",
"ho chi minh":"Asia/Ho_Chi_Minh",
"hobart":"Australia/Hobart",
"hong kong":"Asia/Hong_Kong",
"honolulu":"Pacific/Honolulu",
"hovd":"Asia/Hovd",
"indiana-starke":"US/Indiana-Starke",
"indianapolis":"America/Indiana/Indianapolis",
"indianapolis":"America/Indianapolis",
"inuvik":"America/Inuvik",
"iqaluit":"America/Iqaluit",
"irkutsk":"Asia/Irkutsk",
"isle of man":"Europe/Isle_of_Man",
"istanbul":"Asia/Istanbul",
"istanbul":"Europe/Istanbul",
"jakarta":"Asia/Jakarta",
"jamaica":"America/Jamaica",
"jan mayen":"Atlantic/Jan_Mayen",
"jayapura":"Asia/Jayapura",
"jersey":"Europe/Jersey",
"jerusalem":"Asia/Jerusalem",
"johannesburg":"Africa/Johannesburg",
"johnston":"Pacific/Johnston",
"juba":"Africa/Juba",
"jujuy":"America/Argentina/Jujuy",
"jujuy":"America/Jujuy",
"juneau":"America/Juneau",
"kabul":"Asia/Kabul",
"kaliningrad":"Europe/Kaliningrad",
"kamchatka":"Asia/Kamchatka",
"kampala":"Africa/Kampala",
"kanton":"Pacific/Kanton",
"karachi":"Asia/Karachi",
"kashgar":"Asia/Kashgar",
"kathmandu":"Asia/Kathmandu",
"katmandu":"Asia/Katmandu",
"kerguelen":"Indian/Kerguelen",
"khandyga":"Asia/Khandyga",
"khartoum":"Africa/Khartoum",
"kiev":"Europe/Kiev",
"kigali":"Africa/Kigali",
"kinshasa":"Africa/Kinshasa",
"kiritimati":"Pacific/Kiritimati",
"kirov":"Europe/Kirov",
"knox":"America/Indiana/Knox",
"knox in":"America/Knox_IN",
"kolkata":"Asia/Kolkata",
"kosrae":"Pacific/Kosrae",
"kralendijk":"America/Kralendijk",
"krasnoyarsk":"Asia/Krasnoyarsk",
"kuala lumpur":"Asia/Kuala_Lumpur",
"kuching":"Asia/Kuching",
"kuwait":"Asia/Kuwait",
"kwajalein":"Pacific/Kwajalein",
"kyiv":"Europe/Kyiv",
"la paz":"America/La_Paz",
"la rioja":"America/Argentina/La_Rioja",
"lagos":"Africa/Lagos",
"lhi":"Australia/LHI",
"libreville":"Africa/Libreville",
"lima":"America/Lima",
"lindeman":"Australia/Lindeman",
"lisbon":"Europe/Lisbon",
"ljubljana":"Europe/Ljubljana",
"lome":"Africa/Lome",
"london":"Europe/London",
"longyearbyen":"Arctic/Longyearbyen",
"lord howe":"Australia/Lord_Howe",
"los angeles":"America/Los_Angeles",
"louisville":"America/Kentucky/Louisville",
"louisville":"America/Louisville",
"lower princes":"America/Lower_Princes",
"luanda":"Africa/Luanda",
"lubumbashi":"Africa/Lubumbashi",
"lusaka":"Africa/Lusaka",
"luxembourg":"Europe/Luxembourg",
"macao":"Asia/Macao",
"macau":"Asia/Macau",
"maceio":"America/Maceio",
"macquarie":"Antarctica/Macquarie",
"madeira":"Atlantic/Madeira",
"madrid":"Europe/Madrid",
"magadan":"Asia/Magadan",
"mahe":"Indian/Mahe",
"majuro":"Pacific/Majuro",
"makassar":"Asia/Makassar",
"malabo":"Africa/Malabo",
"maldives":"Indian/Maldives",
"malta":"Europe/Malta",
"managua":"America/Managua",
"manaus":"America/Manaus",
"manila":"Asia/Manila",
"maputo":"Africa/Maputo",
"marengo":"America/Indiana/Marengo",
"mariehamn":"Europe/Mariehamn",
"marigot":"America/Marigot",
"marquesas":"Pacific/Marquesas",
"martinique":"America/Martinique",
"maseru":"Africa/Maseru",
"matamoros":"America/Matamoros",
"mauritius":"Indian/Mauritius",
"mawson":"Antarctica/Mawson",
"mayotte":"Indian/Mayotte",
"mazatlan":"America/Mazatlan",
"mbabane":"Africa/Mbabane",
"mcmurdo":"Antarctica/McMurdo",
"melbourne":"Australia/Melbourne",
"mendoza":"America/Argentina/Mendoza",
"mendoza":"America/Mendoza",
"menominee":"America/Menominee",
"merida":"America/Merida",
"metlakatla":"America/Metlakatla",
"mexico city":"America/Mexico_City",
"michigan":"US/Michigan",
"midway":"Pacific/Midway",
"minsk":"Europe/Minsk",
"miquelon":"America/Miquelon",
"mogadishu":"Africa/Mogadishu",
"monaco":"Europe/Monaco",
"moncton":"America/Moncton",
"monrovia":"Africa/Monrovia",
"monterrey":"America/Monterrey",
"montevideo":"America/Montevideo",
"monticello":"America/Kentucky/Monticello",
"montreal":"America/Montreal",
"montserrat":"America/Montserrat",
"moscow":"Europe/Moscow",
"mountain":"Canada/Mountain",
"mountain":"US/Mountain",
"muscat":"Asia/Muscat",
"nairobi":"Africa/Nairobi",
"nassau":"America/Nassau",
"nauru":"Pacific/Nauru",
"ndjamena":"Africa/Ndjamena",
"new salem":"America/North_Dakota/New_Salem",
"new york":"America/New_York",
"newfoundland":"Canada/Newfoundland",
"niamey":"Africa/Niamey",
"nicosia":"Asia/Nicosia",
"nicosia":"Europe/Nicosia",
"nipigon":"America/Nipigon",
"niue":"Pacific/Niue",
"nome":"America/Nome",
"norfolk":"Pacific/Norfolk",
"noronha":"America/Noronha",
"north":"Australia/North",
"nouakchott":"Africa/Nouakchott",
"noumea":"Pacific/Noumea",
"novokuznetsk":"Asia/Novokuznetsk",
"novosibirsk":"Asia/Novosibirsk",
"nsw":"Australia/NSW",
"nuuk":"America/Nuuk",
"ojinaga":"America/Ojinaga",
"omsk":"Asia/Omsk",
"oral":"Asia/Oral",
"oslo":"Europe/Oslo",
"ouagadougou":"Africa/Ouagadougou",
"pacific":"Canada/Pacific",
"pacific":"US/Pacific",
"pago pago":"Pacific/Pago_Pago",
"palau":"Pacific/Palau",
"palmer":"Antarctica/Palmer",
"panama":"America/Panama",
"pangnirtung":"America/Pangnirtung",
"paramaribo":"America/Paramaribo",
"paris":"Europe/Paris",
"perth":"Australia/Perth",
"petersburg":"America/Indiana/Petersburg",
"phnom penh":"Asia/Phnom_Penh",
"phoenix":"America/Phoenix",
"pitcairn":"Pacific/Pitcairn",
"podgorica":"Europe/Podgorica",
"pohnpei":"Pacific/Pohnpei",
"ponape":"Pacific/Ponape",
"pontianak":"Asia/Pontianak",
"port moresby":"Pacific/Port_Moresby",
"port of spain":"America/Port_of_Spain",
"port-au-prince":"America/Port-au-Prince",
"porto acre":"America/Porto_Acre",
"porto velho":"America/Porto_Velho",
"porto-novo":"Africa/Porto-Novo",
"prague":"Europe/Prague",
"puerto rico":"America/Puerto_Rico",
"punta arenas":"America/Punta_Arenas",
"pyongyang":"Asia/Pyongyang",
"qatar":"Asia/Qatar",
"qostanay":"Asia/Qostanay",
"queensland":"Australia/Queensland",
"qyzylorda":"Asia/Qyzylorda",
"rainy river":"America/Rainy_River",
"rankin inlet":"America/Rankin_Inlet",
"rarotonga":"Pacific/Rarotonga",
"recife":"America/Recife",
"regina":"America/Regina",
"resolute":"America/Resolute",
"reunion":"Indian/Reunion",
"reykjavik":"Atlantic/Reykjavik",
"riga":"Europe/Riga",
"rio branco":"America/Rio_Branco",
"rio gallegos":"America/Argentina/Rio_Gallegos",
"riyadh":"Asia/Riyadh",
"rome":"Europe/Rome",
"rosario":"America/Rosario",
"rothera":"Antarctica/Rothera",
"saigon":"Asia/Saigon",
"saipan":"Pacific/Saipan",
"sakhalin":"Asia/Sakhalin",
"salta":"America/Argentina/Salta",
"samara":"Europe/Samara",
"samarkand":"Asia/Samarkand",
"samoa":"Pacific/Samoa",
"samoa":"US/Samoa",
"san juan":"America/Argentina/San_Juan",
"san luis":"America/Argentina/San_Luis",
"san marino":"Europe/San_Marino",
"santa isabel":"America/Santa_Isabel",
"santarem":"America/Santarem",
"santiago":"America/Santiago",
"santo domingo":"America/Santo_Domingo",
"sao paulo":"America/Sao_Paulo",
"sao tome":"Africa/Sao_Tome",
"sarajevo":"Europe/Sarajevo",
"saratov":"Europe/Saratov",
"saskatchewan":"Canada/Saskatchewan",
"scoresbysund":"America/Scoresbysund",
"seoul":"Asia/Seoul",
"shanghai":"Asia/Shanghai",
"shiprock":"America/Shiprock",
"simferopol":"Europe/Simferopol",
"singapore":"Asia/Singapore",
"sitka":"America/Sitka",
"skopje":"Europe/Skopje",
"sofia":"Europe/Sofia",
"south":"Australia/South",
"south georgia":"Atlantic/South_Georgia",
"south pole":"Antarctica/South_Pole",
"srednekolymsk":"Asia/Srednekolymsk",
"st barthelemy":"America/St_Barthelemy",
"st helena":"Atlantic/St_Helena",
"st johns":"America/St_Johns",
"st kitts":"America/St_Kitts",
"st lucia":"America/St_Lucia",
"st thomas":"America/St_Thomas",
"st vincent":"America/St_Vincent",
"stanley":"Atlantic/Stanley",
"stockholm":"Europe/Stockholm",
"swift current":"America/Swift_Current",
"sydney":"Australia/Sydney",
"syowa":"Antarctica/Syowa",
"tahiti":"Pacific/Tahiti",
"taipei":"Asia/Taipei",
"tallinn":"Europe/Tallinn",
"tarawa":"Pacific/Tarawa",
"tashkent":"Asia/Tashkent",
"tasmania":"Australia/Tasmania",
"tbilisi":"Asia/Tbilisi",
"tegucigalpa":"America/Tegucigalpa",
"tehran":"Asia/Tehran",
"tel aviv":"Asia/Tel_Aviv",
"tell city":"America/Indiana/Tell_City",
"thimbu":"Asia/Thimbu",
"thimphu":"Asia/Thimphu",
"thule":"America/Thule",
"thunder bay":"America/Thunder_Bay",
"tijuana":"America/Tijuana",
"timbuktu":"Africa/Timbuktu",
"tirane":"Europe/Tirane",
"tiraspol":"Europe/Tiraspol",
"tokyo":"Asia/Tokyo",
"tomsk":"Asia/Tomsk",
"tongatapu":"Pacific/Tongatapu",
"toronto":"America/Toronto",
"tortola":"America/Tortola",
"tripoli":"Africa/Tripoli",
"troll":"Antarctica/Troll",
"truk":"Pacific/Truk",
"tucuman":"America/Argentina/Tucuman",
"tunis":"Africa/Tunis",
"ujung pandang":"Asia/Ujung_Pandang",
"ulaanbaatar":"Asia/Ulaanbaatar",
"ulan bator":"Asia/Ulan_Bator",
"ulyanovsk":"Europe/Ulyanovsk",
"urumqi":"Asia/Urumqi",
"ushuaia":"America/Argentina/Ushuaia",
"ust-nera":"Asia/Ust-Nera",
"uzhgorod":"Europe/Uzhgorod",
"vaduz":"Europe/Vaduz",
"vancouver":"America/Vancouver",
"vatican":"Europe/Vatican",
"vevay":"America/Indiana/Vevay",
"victoria":"Australia/Victoria",
"vienna":"Europe/Vienna",
"vientiane":"Asia/Vientiane",
"vilnius":"Europe/Vilnius",
"vincennes":"America/Indiana/Vincennes",
"virgin":"America/Virgin",
"vladivostok":"Asia/Vladivostok",
"volgograd":"Europe/Volgograd",
"vostok":"Antarctica/Vostok",
"wake":"Pacific/Wake",
"wallis":"Pacific/Wallis",
"warsaw":"Europe/Warsaw",
"west":"Australia/West",
"west":"Brazil/West",
"whitehorse":"America/Whitehorse",
"winamac":"America/Indiana/Winamac",
"windhoek":"Africa/Windhoek",
"winnipeg":"America/Winnipeg",
"yakutat":"America/Yakutat",
"yakutsk":"Asia/Yakutsk",
"yancowinna":"Australia/Yancowinna",
"yangon":"Asia/Yangon",
"yangon":"Asia/Yangon",
"yap":"Pacific/Yap",
"yekaterinburg":"Asia/Yekaterinburg",
"yellowknife":"America/Yellowknife",
"yerevan":"Asia/Yerevan",
"yukon":"Canada/Yukon",
"zagreb":"Europe/Zagreb",
"zaporozhye":"Europe/Zaporozhye",
"zurich":"Europe/Zurich"}